# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7aa14133dbd3b9c817a4323a80f26d4c62f5b70ab143a0de17ee42755609ae804ac39fd071e9ce800a55f4374e297623f23f3c4470b52ed166c8818ac1a2bbd9

test:
  secret_key_base: 18c6931adb433f2d65864b558c34042b4dd1c0724010089f0c657cbc678fc47306aac188beaeb2662fe941d5533cbd8985c07c76bc8fdcbe11bdff5c3fd960b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
